### ISSUE TITLE
Steam broken on Steam Os 3.4 update on the steam deck

### ISSUE THREAD

**Issue by DKRacingFan** [LukeShortCloud/winesapOS#565] opened 2023-02-25 22:01 UTC
When I complete the setup and reboot and attempt to launch steam on the SteamDeck, Steam updates, but after the update steam doesn't open. Tried installing through discover too but that dosen't work either.

**Comment by LukeShortCloud** [comment] 2023-02-25 23:34
@DKRacingFan Thanks for reporting this issue! This could be an issue with the graphics driver.

Could you open up "Konsole" or "Terminator", run these commands, and then upload the output of those to this GitHub issue?

```
steam-runtime -gamepadui
```

```
glxinfo | grep renderer
vulkaninfo | grep driverName
```

The first should show the logs of why Steam is not launching. The next two commands will output what OpenGL and Vulkan driver is being used, respectively.

**Comment by DKRacingFan** [comment] 2023-02-26 00:37
[winesap@winesapos ~]$ steam-runtime -gamepadui
steam.sh[12004]: Running Steam on arch rolling 64-bit
steam.sh[12004]: STEAM_RUNTIME is enabled automatically
setup.sh[12078]: Steam runtime environment up-to-date!
steam.sh[12004]: Steam client's requirements are satisfied
[2023-02-25 18:33:21] Startup - updater built Feb 14 2023 00:47:09
[2023-02-25 18:33:21] Startup - Steam Client launched with: '/home/winesap/.local/share/Steam/ubuntu12_32/steam' '-gamepadui'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-02-25 18:33:21] Loading cached metrics from disk (/home/winesap/.local/share/Steam/package/steam_client_metrics.bin)
[2023-02-25 18:33:21] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-02-25 18:33:21] Using the following download hosts for Public, Realm steamglobal
[2023-02-25 18:33:21] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-02-25 18:33:21] Checking for update on startup
[2023-02-25 18:33:21] Checking for available updates...
[2023-02-25 18:33:21] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2023-02-25 18:33:21] Manifest download: send request
[2023-02-25 18:33:21] Manifest download: waiting for download to finish
[2023-02-25 18:33:21] Manifest download: finished
[2023-02-25 18:33:21] Download skipped: /client/steam_client_ubuntu12 version 1676336721, installed version 1676336721, existing pending version 0
[2023-02-25 18:33:21] Nothing to do
[2023-02-25 18:33:21] Verifying installation...
[2023-02-25 18:33:21] Performing checksum verification of executable files
[2023-02-25 18:33:22] Verification complete
Loaded SDL version 3.0.0-765-gc4db0725e
OpenGL GLX extension not supported by display
OpenGL GLX extension not supported by displaysrc/steamUI/Main.cpp (425) : Assertion Failed: Error: OpenGL GLX extension not supported by display
src/steamUI/Main.cpp (425) : Assertion Failed: Error: OpenGL GLX extension not supported by display
assert_20230225183322_6.dmp[12157]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230225183322_6.dmp
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:12144): Gtk-WARNING **: 18:33:22.794: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf5f8edb0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf5f8d500
GetWin32Stats: display was not open yet, good
ComputeStartupMode: forcing gamepadui via clisteamwebhelper.sh[12161]: Runtime for steamwebhelper: defaulting to /home/winesap/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[12161]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[12161]: CEF sandbox already disabled
glXChooseVisual failed
glXChooseVisual failedsrc/steamUI/Main.cpp (425) : Assertion Failed: Error: glXChooseVisual failed
src/steamUI/Main.cpp (425) : Assertion Failed: Error: glXChooseVisual failed
crash_20230225183322_8.dmp[12184]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230225183322_8.dmp
/home/winesap/.local/share/Steam/steam.sh: line 798: 12144 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
[winesap@winesapos ~]$ assert_20230225183322_6.dmp[12157]: Finished uploading minidump (out-of-process): success = yes
assert_20230225183322_6.dmp[12157]: response: CrashID=bp-e61cfdcc-e86d-4cd6-a257-f4c162230225
assert_20230225183322_6.dmp[12157]: file ''/tmp/dumps/assert_20230225183322_6.dmp'', upload yes: ''CrashID=bp-e61cfdcc-e86d-4cd6-a257-f4c162230225''
crash_20230225183322_8.dmp[12184]: Finished uploading minidump (out-of-process): success = yes
crash_20230225183322_8.dmp[12184]: response: CrashID=bp-fa87572b-e134-408b-9d3b-428882230225
crash_20230225183322_8.dmp[12184]: file ''/tmp/dumps/crash_20230225183322_8.dmp'', upload yes: ''CrashID=bp-fa87572b-e134-408b-9d3b-428882230225''
[winesap@winesapos ~]$

**Comment by DKRacingFan** [comment] 2023-02-26 00:40
[winesap@winesapos ~]$ glxinfo | grep renderer
Error: couldn't find RGB GLX visual or fbconfig


[winesap@winesapos ~]$ ^[[200~vulkaninfo | grep driverName~
bash: $'\E[200~vulkaninfo': command not found
[winesap@winesapos ~]$ vulkaninfo | grep driverName
ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_radeon.so. Ignoring this JSON
ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_lvp.so. Ignoring this JSON
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_MESA_device_select uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.240/vulkaninfo/vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
[winesap@winesapos ~]$

**Comment by DKRacingFan** [comment] 2023-02-26 00:43
[winesap@winesapos ~]$ glxinfo | grep renderer
vulkaninfo | grep driverName
Error: couldn't find RGB GLX visual or fbconfig



ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_radeon.so. Ignoring this JSON
ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_lvp.so. Ignoring this JSON
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_MESA_device_select uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.240/vulkaninfo/vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
[winesap@winesapos ~]$

**Comment by DKRacingFan** [comment] 2023-02-26 01:06
[winesap@winesapos ~]$ glxinfo | grep renderer
vulkaninfo | grep driverName
Error: couldn't find RGB GLX visual or fbconfig
ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_radeon.so. Ignoring this JSON
ERROR: [Loader Message] Code 0 : libLLVM-14.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_lvp.so. Ignoring this JSON
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_MESA_device_select uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /usr/src/debug/vulkan-tools/Vulkan-Tools-1.3.240/vulkaninfo/vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
[winesap@winesapos ~]$

**Comment by LukeShortCloud** [comment] 2023-02-26 02:00
Thank you for that. Steam is saying it cannot use OpenGL. Then the OpenGL and Vulkan drivers are basically complaining that no driver can be found.

What version of winesapOS are you using? 3.2.1? I'll see if I can replicate this issue on my Steam Deck.

**Comment by LukeShortCloud** [comment] 2023-02-26 02:00
And what image are you using: minimal, performance, or secure?

**Comment by DKRacingFan** [comment] 2023-02-26 02:06
> 

I'm using winesapOs 3.2.1 and using performance on my steamdeck.

**Comment by LukeShortCloud** [comment] 2023-02-26 03:46
Thank you for that information. I was able to replicate the issue. The problem is that Arch Linux recently updated the LLVM packages from version 14 to 15. The graphics drivers from SteamOS are built against 14 and are not forward-compatible with 15.

As a partial workaround, you can get 64-bit graphical programs to work by installing the package below. However, Steam is 32-bit and still won't work.

```
sudo pacman -S --noconfirm llvm14-libs
```

I will look into providing the necessary updates via our package repository.

**Comment by LukeShortCloud** [comment] 2023-03-14 22:00
Since we need to rebuild and update Mesa, we have a few options:

(1) Mesa RADV from SteamOS 3.4.6. This is also the Mesa package for SteamOS 3.5.1.

```
_tag=steamos-3.5.1
pkgver=23.1.0_devel.166652.steamos_3.5.1
```

(2) Mesa (everything except RADV) from SteamOS 3.4.6.

```
_tag=radeonsi-3.4.0-2
pkgver=22.2.0.157821.radeonsi_3.4.0_2
```

**Comment by LukeShortCloud** [comment] 2023-03-17 05:30
I went with option # 2 as it is more stable (Mesa 23.1 is not even out yet).

@DKRacingFan you can use these commands to update Mesa to a working version. I have rebuilt the SteamOS 3.4.6 graphics drivers against the latest LLVM 15 which I confirmed fixed issues on my test computers.

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

Let me know if this works for you!

**Comment by DKRacingFan** [comment] 2023-03-17 16:09
It works! Just had to restart my pc first.

**Comment by LukeShortCloud** [comment] 2023-03-17 16:34
That's great, I'm glad it worked! A few others ran into the same issue. I'll let them know as well.

I'll close this GitHub Issue as resolved. Let me know if you run into any other problems!

**Closed by LukeShortCloud** 2023-03-17 16:34 UTC
Labels: bug, release_alpha

**Comment by DKRacingFan** [comment] 2023-03-18 16:33
I forgot to mention that I had to overwrite the files  to make steam work. Perhaps this should be reopened

**Comment by LukeShortCloud** [comment] 2023-07-14 19:46
@DKRacingFan winesapOS 3.3.0 has been released to address the issues you were encountering!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

**Comment by DKRacingFan** [comment] 2023-07-14 22:09
Thanks for letting me know!
