### ISSUE TITLE
packagekitd fills up all RAM

### ISSUE THREAD

**Issue by lucid-cloud-dreams** [LukeShortCloud/winesapOS#697] opened 2023-11-29 10:47 UTC
Hello everyone,

**Describe the bug or feature**
I updated a few days ago to the latest version of winesapos with this version of the script: https://github.com/LukeShortCloud/winesapOS/commit/4913f0f1ceec7f8780f5a170d2c56f7debf0d564

Since then my PC starts to freeze after a few minutes, because the process /var/lib/pakagekitd process eats up all my RAM. It uses all of my 32GB of RAM in just a few minutes and the swap file also gets full. Then the PC freezes and I can only hard reset it.

I can kill this process via htop, but it will appear again after some minutes.

**Issue Type**
- [x] Bug Report
- [ ]  Feature Request
- [ ]  Documentation
- [ ]  Question
- [ ]  Other [Please specify]

**To Reproduce**
I am not sure. But upgrade to the latest version gave me this behavior.

**Expected behavior**
That this process do not need so much RAM.

**Screenshots**
Here I tried to let the upgrade run again. But even if I do nothing the RAM usage goes crazy like hell.
![ResizedImage_2023-11-29_11-31-46_1](https://github.com/LukeShortCloud/winesapOS/assets/110485441/cad284d5-e0c9-4477-9429-9aed92246de0)

**Versions (please complete the following information):**
Version: [ex., 3.3.0]
Image type: Performance
Computer type: [PC]
Graphics vendor: [NVIDIA]
Graphics card: [RTX 3070]
CPU vendor: [AMD]
CPU Modell: [Ryzen 9 5900X]

**Additional context**
And this update uninstalled pipewire, so I had no audio, but I can install it via pacman again it is working again. But thats maybe another topic ;)
Before that the system was rock solid and was very satisfied with the OS! :)

**Comment by lucid-cloud-dreams** [comment] 2023-11-29 13:05
I now have a workaround for this problem.
Here is a little logon script:
`#!/bin/zsh`
`sleep 10`
`sudo systemctl stop packagekit`

I had to to do the sleep command, because otherwise it tried to stop the process before it was started.
So I hope this can help someone with the same problem :)

**Comment by LukeShortCloud** [comment] 2023-11-30 04:14
Hey @lucid-cloud-dreams thanks so much for the detailed report and workaround! Could you also upload the `/etc/winesapos/upgrade*.log` files? You will need root privileges to access those files.

This brings up a much bigger issue that the winesapOS upgrade script should only run if there is an upgrade available. There are a bunch of considerations that are accounted for when a new winesapOS release comes out but could cause issues for users trying to upgrade before a new release is out (we automate all this in the next new release):

- AUR packages are pre-compiled but may need to be re-compiled against newer versions of other packages.
- Arch Linux upgrades may require manual intervention.
- winesapOS packages may require manual intervention.

I added a check for new winesapOS versions in the first-time setup. I need to do the same for the upgrade script to prevent issues like what you encountered.

Let me push the release candidate packages to our stable repository branch. Then you can test the upgrade to winesapOS 3.4.0-rc1, remove your workaround, and see if you are still encountering RAM being filled up by packagekitd. I will let you know when that is available.

**Comment by lucid-cloud-dreams** [comment] 2023-11-30 08:26
Hello @LukeShortCloud ,

thank you very much for your nice and promising answer :)

This log file is where it was the last time rock solid with.
[upgrade_2023-10-29T09:00:23+01:00.log](https://github.com/LukeShortCloud/winesapOS/files/13510294/upgrade_2023-10-29T09.00.23%2B01.00.log)

This log file was created when I was trying the first attempt to update. After that this bug occurred.
[upgrade_2023-11-25T19:04:20+01:00.log](https://github.com/LukeShortCloud/winesapOS/files/13510295/upgrade_2023-11-25T19.04.20%2B01.00.log)

This was the last successful attempt to re run the update, before I was knowing, that it is not a good advice to run the same update multiple times in a row :P
(Lesson learned)
[upgrade_2023-11-29T12:09:26+01:00.log](https://github.com/LukeShortCloud/winesapOS/files/13510296/upgrade_2023-11-29T12.09.26%2B01.00.log)

Do you need anything more?

Have a nice day!

**Comment by LukeShortCloud** [comment] 2023-12-01 03:27
Thank you for providing those logs! That is very helpful.

I noticed at least one issue. There are a few instances of `error: no operation specified` for Pacman in the the first upgrade log.

```
Adding Pacman support to Discover...
+ /usr/local/bin/pacman-static packagekit-qt5
error: no operation specified (use -h for help)
+ echo 'Adding Pacman support to Discover complete.'
```

It does not show up in the newer logs.

```
+zsh:489> echo 'Adding Pacman support to Discover...'
Adding Pacman support to Discover...
+zsh:490> /usr/local/bin/pacman-static --noconfirm -S --needed packagekit-qt5
warning: packagekit-qt5-1.1.1-1 is up to date -- skipping
 there is nothing to do
+zsh:491> echo 'Adding Pacman support to Discover complete.'
Adding Pacman support to Discover complete.
```

My best guess is that with the error and various Pacman commands failing, it actually lead to a seemingly successful upgrade the first time.

Also related, I'm working on preventing upgrades when none are available here: https://github.com/LukeShortCloud/winesapOS/issues/699

**Comment by LukeShortCloud** [comment] 2023-12-01 04:09
I somehow missed your very first sentence! The problem with running the latest upgrade script is that it does not use the latest winesapOS packages. I manually hack the file and pacman.conf to use the "winesapos-testing" repository instead of "winesapos". I have now opened a feature request to add an easier and automated way to do that: https://github.com/LukeShortCloud/winesapOS/issues/700

For the first upgrade, were you using Bash? That would explain why the variable expansion did not work. For historical reasons, all of our scripts only work with Zsh. I can confirm that the behavior matches what I'm seeing in the logs with this short script that reproduces the problem:

```
$ vim test.sh
CMD_PACMAN="/usr/local/bin/pacman-static"
CMD_PACMAN_INSTALL=(${CMD_PACMAN} --noconfirm -S --needed)
echo ${CMD_PACMAN_INSTALL}
$ bash ./test.sh
/usr/local/bin/pacman-static
$ zsh ./test.sh
/usr/local/bin/pacman-static  --noconfirm -S --needed
```

@lucid-cloud-dreams Try running the "winesapOS Upgrade" again. I have now pushed the latest packages from winesapos-testing to the stable winesapos repository as part of releasing 3.4.0-rc.0 tonight. After a reboot and removing the packagekit workarounds you have, are you still seeing increased RAM usage?

**Comment by lucid-cloud-dreams** [comment] 2023-12-01 09:37
Hello @LukeShortCloud,

I kind of just did what you said.
re-run the update:
`curl https://raw.githubusercontent.com/LukeShortCloud/winesapOS/stable/scripts/winesapos-upgrade.sh | sudo -E zsh`
then removed my workaround during the update process (reason down below) and rebooted. The error still occurred.

While the update was running there where this line with `Refresh PackageKit` several times. And it stuck there always for some seconds.
![Screenshot_20231201_094231](https://github.com/LukeShortCloud/winesapOS/assets/110485441/c6740c04-047c-4586-b7ab-0fd16b846860)
![Screenshot_20231201_094839](https://github.com/LukeShortCloud/winesapOS/assets/110485441/ff87d0b2-e07a-46c5-8d70-020047086c37)
After the second screenshot I re-enabled the packagekitd Service with removing the _ in the path, but didn't start the service manually. After a minute or so, it started on his own again and since then I had the problem again.

Should I re-run the update again, without removing the _ of the Service again?

And here is the logfile:
[upgrade_2023-12-01T09:30:56+01:00.log](https://github.com/LukeShortCloud/winesapOS/files/13523514/upgrade_2023-12-01T09.30.56%2B01.00.log)

As far as I am aware of, I never run the update script with bash. I always run the command you provide in your documentation.

**Comment by LukeShortCloud** [comment] 2023-12-02 02:26
By the way, regarding PipeWire being uninstalled, that happened because the package name changed in upstream Arch Linux. winesapOS takes care of his by removing the old package and installing the new one. Because `${CMD_PACMAN_INSTALL}` did not work on the first upgrade, the new package was never installed. I see that the variable has been working for all of your other upgrades. I know you said you used Zsh each time but using another shell is the only reason I can think of as to why that would happen. I am adding in safeguards to prevent this issue from happening again in the future.

**Comment by LukeShortCloud** [comment] 2023-12-02 03:37
To help fix your system / allow future upgrades to continue to work, make sure these packages are installed. I noticed a few important ones (such as `python-crudini`, which is heavily used by the winesapOS upgrade process) was missing due to same issue encountered with PipeWire (the old package was removed and the new package failed to install):

```
sudo pacman -S \
  qt5-tools \
  kdialog \
  glibc \
  archlinux-appstream-data \
  kate \
  xed \
  linux-firmware \
  clang \
  wireplumber \
  grub-theme-vimix \
  libpipewire \
  packagekit-qt5 \
  cifs-utils \
  nfs-utils \
  erofs-utils \
  f2fs-tools \
  mtools \
  reiserfsprogs \
  mangohud \
  fprintd \
  plasma-wayland-session \
  jfsutils \
  openrazer-daemon \
  gwenview
```

```
yay -S game-devices-udev python-crudini python-iniparse
```

**Comment by LukeShortCloud** [comment] 2023-12-05 02:30
If nothing else, the links about PackageKit help me understand how much it sucks. :-) I've gone back and forth about what a good GUI package manager to use is and the perfect one simply doesn't exist. I settled for adding Discover to align with the Steam Deck but there is also the "Applications" (bauh) app we install but it's less polished.

Wow, that is awful that your RAM and swap gets filled in 4 minutes (before the `packagekitd` daemon even turns off!). Good to know. I'll leave a mention about this in the release notes with the workaround in case others run into this problem.

Thanks again for the report! I don't need anything else, you've already been a huge help! I'll go ahead and close this issue out. Happy gaming!

**Closed by LukeShortCloud** 2023-12-05 02:30 UTC
Labels: bug
