### ISSUE TITLE
Error when booting? How can i fix this, im a linux noob

### ISSUE THREAD

**Issue by Psyykosis** [LukeShortCloud/winesapOS#637] opened 2023-07-24 12:50 UTC
mount: /new_root: wrong fs type, bad option, bad superblock on /dev/sdat, missing codepage or helper program, or other error. dmesg (1) may have more information after failed mount system call.

ERROR: Failed to mount 'UUID=3d9ca768-9826-42b4-a116-f3ab4168f296' on real root You are now being dropped into an emergency shell. sh: can't access tty: job control turned off [rootfs ~]#

**Comment by LukeShortCloud** [comment] 2023-07-24 17:16
@Psyykosis Thanks for reporting this issue!

What version of winesapOS (3.3.0?) and image type (minimal, performance, or secure) are you using? I'll see if I can replicate the issue.

**Comment by LukeShortCloud** [comment] 2023-08-23 20:28
I was able to figure out, based on the UUID, that this is the winesapOS 3.3.0 minimal image. I could not replicate the issue on any of my computers.

@Psyykosis What are the hardware specs of your PC or Mac? I see it says `/dev/sdat` which means that either (1) it was a simple typo or (2) you have a lot of storage devices on your computer (around 40?). Also try all of the available GRUB menu options ("Arch Linux, with linux-lts", "Arch Linux, with linux-lts (fallback initramfs)", "Arch Linux, with linux-lts515", and "Arch Linux, with linux-lts515 (fallback initramfs").

**Comment by LukeShortCloud** [comment] 2023-09-20 23:48
It has been a couple of months now. Here are my final thoughts before I close this out:

- `/dev/sdat` from your error message means that the drive you have winesapOS on is the 46th SCSI/SATA drive in your system. I do not have a system with the amount of drives or SATA ports anywhere near that so I cannot reproduce that use-case.
- A different Linux kernel may provide better driver support. I recommend selecting "Linux LTS" at boot.
- Try using a different image such as the Performance image. That will have more hardware firmware installed so it'll boot on more systems.

If you ever try out winesapOS again, please let me know and I'd be able to help to troubleshoot further!

**Closed by LukeShortCloud** 2023-09-20 23:48 UTC
Labels: bug

**Comment by LukeShortCloud** [comment] 2024-01-12 05:27
@Psyykosis If you are on a Steam Deck, you need to update to SteamOS 3.5.11 or newer. Otherwise, you can try out our new winesapOS 3.4.0 release to see if that works better for you.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
